name: Extract Sourcecode 7z
on:
  push:
    paths: 
      - 'sourcecode.7z'  # Trigger only for .7z files
jobs:
  extract-and-commit:
    runs-on: ubuntu-latest
    permissions: 
      contents: write # bot to save the folder after extraction
    steps:
      - name: Catch the Code
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: sudo apt-get install -y p7zip-full

      - name: Extract the sourcecode.7z
        run:  |
          # Check if file exist (Notice the spaces!)
          if [ -f "sourcecode.7z" ]; then
            echo "Found sourcecode.7z! Extracting..."

            # 'x' means extract with full paths (keeps folders intact)
            # '-y' means yes to all prompts
            7z x sourcecode.7z -y

            # delete the .7z file 
            rm sourcecode.7z
          
          else
            echo "No Source code 7z file found"
          fi

      - name: Save the extracted folder to github
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-extracted project from sourcecode.7z " || echo "Nothing to commit"
          git push
